config/routes.rb
Rails.application.routes.draw do


  resources :reviews do
    member do
      put 'helpful' => 'reviews#helpful'
      put 'unhelpful' => 'reviews#unhelpful'
    end
  end

  resources :charges
  resources :genres
  resources :notifications do
    collection do
      post :mark_as_read
   end
 end
  resources :books do
    get :claim, on: :member
    get :unclaim, on: :member
    resources :reviews
  end

  get 'user/:id' => 'users#show', as: 'user'
  get 'reviewers' => 'users#reviewer', as: 'reviewers'
  get 'authors' => 'users#author', as: 'authors'
  get 'current_user' => 'users#profile'
  get 'edit_user' => 'users#edit'
  get 'authors_search', to: 'users#author'
  get 'reviewers_search', to: 'users#reviewer'


  get 'new_author' => 'users#new_author'
  get 'new_reviewer' => 'users#new_reviewer'

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }

  root to: 'home_pages#index'

  get 'admin' => 'reviews#index'


  get 'author_signup' => 'home_pages#author_signup'
  get 'reviewer_signup' => 'home_pages#reviewer_signup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
mount_uploader :avatar, AvatarUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :reviews , dependent: :destroy
  has_many :notifications, foreign_key: :recipient_id

  enum access_level: [:author, :reviewer, :moderator]

  has_and_belongs_to_many :claims, join_table: :books_users, association_foreign_key: :book_id, class_name: Book.to_s

def self.search(search)
  where("concat_ws(' ', first_name, last_name) ILIKE ?", "%#{search.squish}%")
end

def full_name
  first_name + " " + last_name
end

def score
  self.reviews.where(helpful: true)
end

def count_increases
  @array = self.reviews.size
  if @array += 1
    self.increment!(:ranking, 2)
  end
end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  prepend_before_action :require_no_authentication, only: :cancel

  #GET /resource/sign_up
   #def new
    # super
   #end

   #POST /resource


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:access_level])
   end

   def after_sign_up_path_for(resource)
     current_user_path
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

 def sign_up_params
   params.require(:user).permit(:avatar, :bio, :ranking, :access_level, :first_name, :last_name, :email, :password, :password_confirmation)
 end

 def account_update_params
   params.require(:user).permit(:bio, :ranking, :avatar, :first_name, :last_name, :email, :password, :password_confirmation, :current_password)
 end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in

  # def new
  #   super
  # end

  # POST /resource/sign_in

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected

   def after_sign_in_path_for(resource)
     if current_user.author? || current_user.reviewer?
       current_user_path
     else
     reviews_path
    end
   end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new_author
    @user = User.new
  end

  def new_reviewer
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user.books.each do |b|
    @avg_rating = if b.reviews.blank?
    0
    else
      b.reviews.average(:rating).round(2)
    end
  end
  end


  def profile
    @current_user = current_user
    @helpful = current_user.reviews.where(helpful: true)
    @unhelpful = current_user.reviews.where(unhelpful: true)
    @reviews = current_user.reviews
    unhelpful = @unhelpful.count
    total = @reviews.count
    subtotal = total - unhelpful
    @score = subtotal.to_f / total

  end

  def reviewer
    if params[:search]
      @reviewers_search = User.search(params[:search]).paginate(:page => params[:page], :per_page => 2)
    else
      @reviewers_search = User.where(access_level: :reviewer).order('first_name ASC').paginate(:page => params[:page], :per_page => 2)
    end
  end

  def author
      if params[:search]
        @authors_search = User.search(params[:search]).paginate(:page => params[:page], :per_page => 2)
        @author_rank = b.reviews.count 
      else
        @authors_search = User.where(access_level: :author).order('first_name ASC').paginate(:page => params[:page], :per_page => 2)
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:bio, :ranking, :first_name, :last_name, :email, :password, :avatar, :access_level)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/users/author.html.erb
<div id="author_search_bar">
	<%= form_tag(authors_search_path, method: "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search Authors"%>
	<%= submit_tag "Search" %>
<% end %>
</div>

  	 
 <div id="author-records-container"> 	   
  	 <div id="author_pagination">
  	 	<%= will_paginate @authors_search %>
  	 </div>
<% @authors_search.each do |s| %>
  	 <div id="author-index-container">


	    <%= link_to s.full_name, user_path(s) %>
	    <%= image_tag s.avatar_url(:thumb).to_s %>

     <%= s.books.collect(&:reviews).count %> reviews
     Ranking: 
     <% if s.ranking == nil %>
      0
      <% else %>
        <%= s.ranking %>
      <% end %>
    
  	</div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(current_user, url: registration_path(current_user), html: { method: :put }) do |f| %>

<div id="user-edit-form">
  <h2>Edit <%= current_user.full_name %></h2><br />

  <div class="profile-pic">
    <%= f.label "Profile Pic" %>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.text_area :bio, placeholder: "Tell your story...", :rows => 5, :cols => 30 %>
  </div>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
</div>

<div id="cancel-account">
<h3>Cancel my account</h3><br />
<p>Unhappy? <%= button_to "Cancel my account", registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete %></p>
</div>

app/views/users/index.html.erb
<%= 

app/views/users/new_author.html.erb
<%= form_for(@user, url: registration_path(@user)) do |f| %>
<div class="registration-container">
  <h2>Sign up today!</h2>

  <div class="profile-pic">
    <%= f.label "Add a profile pic" %><br />
    <%= f.file_field :avatar, class: "select_button" %>
  </div><br />
  <div class="user-roles">
    <%= f.select(:access_level, [['Author', 'author']]) %>
  </div><br />

  <div class="field">
    <%= f.text_area :bio, placeholder: "Tell your story...", :rows => 5, :cols => 30 %>
  </div>

  <div class="user-name">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br />
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div><br />

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
</div>
<% end %>

app/views/users/new_reviewer.html.erb
<%= form_for(@user, url: registration_path(@user)) do |f| %>
<div class="registration-container">
  <h2>Sign up today!</h2>

  <div class="profile-pic">
    <%= f.label "Add a profile pic" %><br />
    <%= f.file_field :avatar %>
  </div><br />
  <div class="user-roles">
    <%= f.select(:access_level, [['Reviewer', 'reviewer']]) %>
  </div><br />

  <div class="user-name">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %><br />
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div><br />

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
</div>
<% end %>

app/views/users/profile.html.erb
<!DOCTYPE html>

<% if current_user.author? %>

  
    <div id="profile-pic-container">
      <%= image_tag current_user.avatar_url(:small).to_s, class: "img-fluid", style: "border-radius: 50%"  %><br />
    </div>
    <h1 id="author_welcome">Welcome Author, <%= current_user.full_name %></h1>

    <div id="new-book-upload">
      <%= link_to image_tag("icons8-plus-64.png"), new_book_path %><br />
    </div>
    <% end %>

  <% if current_user.author? & current_user.books.blank? %>

 
    <div id="no_books">
      << You don't have any books yet, upload one now
    </div>


    <% else %>
  

      <% current_user.books.each do |b| %>


    <div id="author-profile-books">
        <%= image_tag b.avatar_url(:small).to_s, class: "img-fluid" %>
        <b><%= b.title %></b><br />
        <p><%= b.description.html_safe %></p><br />
        <b>Genres:</b> <%= b.genres.map { |x| x.name }.join(',') %><br />

        <div id="book_edit_icons"><%= link_to image_tag("icons8-pencil-24.png"), edit_book_path(b) %><%= link_to image_tag("icons8-delete-16.png"), book_path(b), method: :delete %>
        </div>
      </div>
      <% end %>
    <% end %>


<% if current_user.reviewer? %>

<body>
  <div id="profile-pic-container">
    <%= image_tag current_user.avatar_url(:small).to_s, class: "img-fluid", style: "border-radius: 50%"  %>
    <div id="scorecard-container">
        <h3 id="scorecard-header">My Scorecard</h3>


        <table id="scorecard-table">
          <th>Total Reviews</th>
          <th>Helpful</th>
          <th>Unhelpful</th>
          <th>Score</th>

          <tr id="scorecard">
            <td><%= current_user.reviews.count %></td>
            <td><%= @helpful.count %></td>
            <td><%= @unhelpful.count %></td>
            <td><%= number_to_percentage(@score * 100, precision: 0) %></td>

          </tr>
        </table>
    </div>
  </div>

    <div id="profile-container">

      <div id="reviewer_name_banner">
        <h2>Welcome Reviewer, <%= current_user.full_name %></h2><br />
        <h3><b>Currently Reading</b></h3>
      </div>

    

    <div id="currently-reading">
      <% current_user.claims.each do |c| %>
         <%= link_to image_tag(c.avatar_url(:small).to_s), c, id: "currently-reading-link" %>
      <% end %>
    </div>
    <div id="next_book_link">
      <%= link_to "Your next book", genres_path, id: "next-book" %>
    </div>
    <% end %>
  </div>
</body>

app/views/users/reviewer.html.erb
<div id="reviewers_search_bar">
  <%= form_tag(reviewers_search_path, method: "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Authors"%>
  <%= submit_tag "Search" %>
<% end %>
</div>

     
 <div id="reviewer_records_container">     
     <div id="reviewer_pagination">
      <%= will_paginate @reviewers_search %>
     </div>
<% @reviewers_search.each do |s| %>
     <div id="reviewer-index-container">


      <%= link_to s.full_name, user_path(s) %>
      <%= image_tag s.avatar_url(:thumb).to_s %>
          
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>


<body>
<div id="user-show-profile-pic">
  <%= image_tag @user.avatar_url(:thumb).to_s, class: "img-fluid" %><b><%= @user.full_name %></b><br />
</div>

<% if @user.author? %>

<div id="author_bio">
  <h3>About <%= @user.first_name %></h3>
  <p id="bio_text">
    
    <script>
      $(window).on("load", function(){
        $(".read-less-<%= @user.id %>").addClass("hide");
      });
    </script>

    <% if @user.bio.blank?%>
          
          <div>
            <p>
              No bio yet :(
            </p>
          </div>

    <% elsif @user.bio.length > 150 %>
      <%= truncate(@user.bio, escape: false, length: 120) %>
      <%= link_to "read more", '', class: "read-more-#{@user.id}" %>
       <%= link_to "read less", '', class: "read-less-#{@user.id}"%>
      <script>
        $(".read-more-<%= @user.id %>").on("click", function(e){
          e.preventDefault()
          $(this).parent().html('<%= escape_javascript @user.bio %>')
           $(".read-less-<%= @user.id %>").addClass("show")
          });
        

           
         
         

       
      </script>


      <% else %>
        
        <% @user.bio %>

    <% end %>
  </p>
</div>

  <% @user.books.each do |b| %>


 

  <div id="author-show-page-book">
    <%= image_tag b.avatar_url(:small).to_s, class: "img-fluid" %>
    <div class='star-rating' data-score=<%= @avg_rating %>></div>
      <em><%= "#{b.reviews.size} reviews" %></em><br />
    Title: <%= link_to b.title, b %><br />
    Description: <b><%= b.description.html_safe %></b><br />
    Genres: <%= b.genres.map { |x| x.name }.join(',') %><br />
  </div>


    <% end %>
<% end %>

<% if @user.reviewer? %>

  <% @user.reviews.each do |r| %>

  <div id="user-reviews">

    <%= link_to image_tag(r.book.avatar_url(:small).to_s), r.book %><br />
    <b><span id="book_title"><%= r.book.title %></span><b><br /> by 
      <%= link_to r.book.user.full_name, r.book.user %><br />
    <div id="actual_review">
      <h2>Review</h2><%= r.created_at.to_date %><br />
        Rating: <div class="star-rating" data-score= <%= r.rating %> ></div>
        <%= @user.first_name %> said: <%= r.comment.html_safe %><br />
        <span><i>**<%= r.unhelpful? %></i></span>
    </div>
  </div><br />

  <% end %>
  <% if !@user.reviews.present? %>
    <p id="no-reviews">No reviews yet :(</p>
    <% end %>
<% end %>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
   
</script>

</body>
>