config/routes.rb
Rails.application.routes.draw do


  resources :reviews do
    member do
      put 'helpful' => 'reviews#helpful'
      put 'unhelpful' => 'reviews#unhelpful'
    end
  end

  resources :charges
  resources :genres
  resources :notifications do
    collection do
      post :mark_as_read
   end
 end
  resources :books do
    get :claim, on: :member
    get :unclaim, on: :member
    resources :reviews
  end

  get 'user/:id' => 'users#show', as: 'user'
  get 'reviewers' => 'users#reviewer', as: 'reviewers'
  get 'authors' => 'users#author', as: 'authors'
  get 'current_user' => 'users#profile'
  get 'edit_user' => 'users#edit'
  get 'authors_search', to: 'users#author'
  get 'reviewers_search', to: 'users#reviewer'


  get 'new_author' => 'users#new_author'
  get 'new_reviewer' => 'users#new_reviewer'

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }

  root to: 'home_pages#index'

  get 'admin' => 'reviews#index'


  get 'author_signup' => 'home_pages#author_signup'
  get 'reviewer_signup' => 'home_pages#reviewer_signup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController

  def index
  end

  def author_signup
  end

  def reviewer_signup
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/author_signup.html.erb
<body>
  <div id="main-author-signup-container">
    <div id="ASH_container">
      <h1 id="author-signup-header"><%= image_tag "icons8-literature-filled-50.png" %> Become an Author With Us!</h1>

    <h3>You're already used to paying for Netflix or Spotify, why not invest into your future success as an author?</h3>
    <div id="netflix">
      <%= image_tag "app-entertainment-ipad-265685.jpg", style: "width:400px;height:400px;" %>
      <p>Movies are good...</p>
    </div>
    <div id="reading-pic">
      <%= image_tag "Canva - Woman sitting on stack of books.jpg", style: "width:400px;height:400px;", class: "img-fluid" %>
        <p>but books are better!</p>
    </div>
    <div id="author-subscription-container">
      <div id="rules" ><p class="rules">Here's how it works. You make your book on Amazon permanently free by
        listing it on other platforms like Smashwords and elsewhere for free and telling
        Amazon you see it free on those sites or by going into your KDP account and making it
        free (temporarily)...that way reviewers "purchase" your book at no charge to them but their Amazon
        review is still a verified Amazon purchase review, the best kind of review to help your
        sales out. Pretty simple, right?</p>
        <p class="mobile-rules"></p>
        <a href="https://www.indiesunlimited.com/2016/03/03/how-to-set-your-book-free-on-amazon/">Make it free guide</a><br />
      </div>

      <h3>Author Subscription Plan</h3>
      <%= image_tag "icons8-five-of-five-stars-64.png" %>
      <p>We've put together a package we know you'll go for.<br>
        Unlimited reviews. Let our community of reviewers put you on the map.</p><p id="paid-sub">Only $9.99/month. Cancel anytime.</p>
        <p><button id="author-sub-button" type="button"><%= link_to "FREE", new_author_path %></button>, for a limited time</p>

    </div>
  </div>
</body>
<script>
  let para = document.getElementById("rules").firstChild.innerHTML;
  let smaller = para.charAt(200);
  let newPara = para - smaller; 

  let para2 = document.querySelector(".mobile-rules");

  if (window.screen.width < 500) {
    document.getElementById("rules").firstChild.style.display = "none";
    var message = document.createElement("P");
    document.querySelector(".rules").appendChild(message).innerHTML = "does this work?";
  }
</script>

app/views/home_pages/index.html.erb
<DOCTYPE! html>
<head>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js">
    </script>
</head>
<body>
<h3 id="main-banner"><i>Write, Read, Review</i></h3>
<button id="left_button" type="button">Author Details</button>
<button id="right_button" type="button">Reviewer Details</button>

<div id="pitch-container">
  
  <div id="author-pitch" class="slide active">
    <h2 id="author-header">Self-published Author?</h2>

    <p>
      Tired of seeing your books on Amazon go nowhere? Looking for a way to boost sales?
    </p>
    <p>
      Take it from me personally, I wasn't interested in buying 5 reviews for $100, and they're not even verified Amazon purchase
      reviews to boot, or reading the cliche blog posts on how to get up in the ranks by
    </p> 
    <p id="truncated">honing your keywords in the description,
      a better cover, and so on. No. Readers like to see validation that a book may be worthwhile. They like to see customer feedback.
      Reviews. Are you in need of them? 
    </p>
    <%= link_to "read on", author_signup_path %>
  </div>
  
  <div id="reviewer-pitch" class="slide">
    <h2 id="reviewer-header">Readers, Looking fo the Next Great Author?</h2>

    <p>
      Have we got the books for you. Hundreds of free titles. Free books in exchange for an honest review. And you feel good helping
      your favorite new author out, what could be better?
    </p>
    <%= link_to "tell me more!", reviewer_signup_path %>
  </div>
</div>
<div id=book_bottom>

</div>
<div class="body-container">
  <h3>Already a member?   <button type="button"><%= link_to "Log in", new_user_session_path, id: "login_link" %></button></h3>

</div>
</body>
<script>

  if ($(window).width() < 600) {
    alert("welcome to mobile!");
  }
  else {
      $("#truncated").addClass("hide");
      $("#truncated").after("<p id='elipses'>...</p>");
      $("#elipses").css("color", "blue");
      $("#elipses").addClass("pointerCursor");
      $("#elipses").on("click", function(){
        $("#truncated").toggle();
      });
  }
    
  $(document).ready(function(){
    function loop () {

      $("h2")
      .animate({ opacity: "0.1"}, 2000)
      .animate({ opacity: "1"}, 3000, loop);
    }
    loop();
  });



$(document).ready(function(){
  $("#reviewer-pitch").addClass("hide");
});

$(document).ready(function(){
  $("#right_button").on("click", function(){
    var currentSlide = $(".active");
    var nextSlide = currentSlide.next();

    currentSlide.fadeOut(1000).removeClass("active");
    nextSlide.fadeIn(1000).addClass("active");

    if (nextSlide.length == 0) {
      $(".slide").first().fadeIn(1000).addClass("active");
    }
  });

  $("#left_button").on("click", function(){
    var currentSlide = $(".active");
    var prevSlide = currentSlide.prev();

    currentSlide.fadeOut(1000).removeClass("active");
    prevSlide.fadeIn(1000).addClass("active");

    if (prevSlide.length == 0) {
      $(".slide").last().fadeIn(1000).addClass("active");
    }
  });
});
  
</script>

app/views/home_pages/reviewer_signup.html.erb
<div id="rsh_container">
  <h1 id="reviewer-signup-header"><%= image_tag "icons8-literature-filled-50.png" %> Become a Reviewer Today! It's FREE</h1>
</div>

<div id="reviewer-subscription-container">
	<div id="reviewer-message">
	  <h3>Books, books galore. Discover the next JK Rowling or Stephen King here!</h3>
	    <p>We offer a unique platform that encourages ordinary people like you and me to share
	      their work of art for free for all to enjoy in exchange for an honest review. Let me help you help me,
	      as they say...or something like that. This community is unlike any other and together we can change the
	      publishing industry and make books great again!
	    </p>
	    <button type="button"><%= link_to "subscribe", new_reviewer_path %></button>
	</div>
    <div id="reviewer_signup_graphic"></div>
</div>