config/routes.rb
Rails.application.routes.draw do


  resources :reviews do
    member do
      put 'helpful' => 'reviews#helpful'
      put 'unhelpful' => 'reviews#unhelpful'
    end
  end

  resources :charges
  resources :genres
  resources :notifications do
    collection do
      post :mark_as_read
   end
 end
  resources :books do
    get :claim, on: :member
    get :unclaim, on: :member
    resources :reviews
  end

  get 'user/:id' => 'users#show', as: 'user'
  get 'reviewers' => 'users#reviewer', as: 'reviewers'
  get 'authors' => 'users#author', as: 'authors'
  get 'current_user' => 'users#profile'
  get 'edit_user' => 'users#edit'
  get 'authors_search', to: 'users#author'
  get 'reviewers_search', to: 'users#reviewer'


  get 'new_author' => 'users#new_author'
  get 'new_reviewer' => 'users#new_reviewer'

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }

  root to: 'home_pages#index'

  get 'admin' => 'reviews#index'


  get 'author_signup' => 'home_pages#author_signup'
  get 'reviewer_signup' => 'home_pages#reviewer_signup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  has_many :reviews, dependent: :destroy 
  has_and_belongs_to_many :genres, dependent: :destroy
  has_and_belongs_to_many :claims, join_table: :books_users, association_foreign_key: :user_id, class_name: User.to_s


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index

    @books = Book.paginate(:page => params[:page], :per_page => 2)

  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @avg_rating = if @book.reviews.blank?
    0
    else
      @book.reviews.average(:rating).round(2)
    end
  end

  def book_author
    @author = @book.user
  end

  # GET /books/new
  def new
    @book = current_user.books.build
    @genres = Genre.all
  end

  # GET /books/1/edit
  def edit
    @genres = Genre.all 
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def claim
    book = Book.find(params[:id])
    book.claims << current_user unless book.claims.include?(current_user)
    redirect_to book, notice: 'Added to reading list'
  end

  def unclaim
    book = Book.find(params[:id])
    if book.claims.include?(current_user)
      book.claims.delete(current_user)
      redirect_to book, notice: 'Done reading'
    end
  end
  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to current_user_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to current_user_path, notice: 'Book was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def book_params
      params[:book][:genre_ids] = (params[:book][:genre_ids] || {}).values.map(&:to_i)
      params.require(:book).permit(:avatar, :title, :user_id, :description, genre_ids: [])
    end
end

app/helpers/books_helper.rb
module BooksHelper
  
end

app/views/books/_form.html.erb
<%= tinymce_assets %>

<div id="book_form_container">
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="new-book-form">
    <div class="field">

      <%= form.hidden_field :user_id %>
    </div>

    <div class="cover-art">
      <%= form.label "Book cover" %>
      <%= form.file_field :avatar %>
    </div>

    <div class="title_field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <p id="amazon-link">**Please be sure to include your link to your book on Amazon in the description. Thank you.**</p>

    <div class="text_field">
      <%= form.label :description %>
      <%= form.text_area :description, :class => "tinymce", :rows => 10, :cols => 30 %>
    </div>

    <div class="genres-field">
      <% @genres.each_with_index do |genre, i| %>
        <%= check_box_tag "book[genre_ids][#{i}]", genre.id %>
        <%= label_tag "book[genre_ids][#{i}]", genre.name %>
      <% end %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>
<script>
tinymce.init({
  selector: 'textarea',
  plugins: [ 'code', 'lists', 'link'],
  mobile: {
    theme: 'mobile',
    plugins: [ 'autosave', 'lists', 'autolink' ],
    toolbar: [ 'link', 'undo', 'bold', 'italic', 'styleselect' ]
    }
  });

</script>
</div>
<%= tinymce %>

app/views/books/_review_form.html.erb
<%= form_with model: @review do |form| %>

  <% form.hidden_field :user_id %>
  <% form.hidden_field :book_id %>

  <%= form.check_box :claim %>

  <%= form.submit :submit %>

<% end %>

app/views/books/edit.html.erb
<h1 id="book_edit_header">Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', current_user_path, style: "color: white; margin-left: 20px;" %>

app/views/books/index.html.erb
<h1 id="books_index_header">Books</h1>

<div id="books_pagination">
  <%= will_paginate @books %>
</div>

<table id="books-table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to image_tag(book.avatar_url(:small).to_s), book %></td>
        <td><b><%= link_to book.user.full_name, book.user %></b></td>
        <td><b><%= book.title %></b></td>
        <td>
         <p><%=  truncate(book.description, :ommision => "...", :length => 200, escape: false) %></p>
       </td>
        <td><%= link_to image_tag("icons8-forward-24.png"), book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/books/new.html.erb
<h1 id="new_book_header">New Book</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<!DOCTYPE html>
<body>
<p id="notice"><%= notice %></p>

<div id="book-show-details">
  <div id="book-cover-container">
    <%= image_tag @book.avatar_url(:small).to_s, class: "img-fluid" %>
  </div>

  <p>
    <strong>Author:</strong>
    <%= @book.user.full_name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @book.title %>
  </p>

  <p>
    <strong>Genres</strong>

    <% @book.genres.each do |g| %>
      <%= link_to g.name, g %>
    <% end %>
  </p>
  <p>
    <strong>Description:</strong>
    <p id="book-description"><%= @book.description.html_safe %></p>
  </p>
</div>
<div id="author-books">
  <b>More Books by this author:</b> <%=link_to @book.user.full_name, user_path(@book.user) %>
</div>


<div id="review-section" style="overflow-x:auto;">
  <strong><h3>Reviews</h3></strong>
  <% if @book.reviews.blank? %>
    <p>This book hasn't received any reviews yet...</p>
  <% else %>
  <div class='star-rating' data-score=<%= @avg_rating %>></div>
    <em><span><%= "#{@book.reviews.size} reviews" %></span></em>
    <% end %>
  <table id="review-table" >


    <tbody>
        <% @book.reviews.each do |r| %>
        <tr id="reviewer-name-stars">
          <td class="reviewer-pic"><%= image_tag r.user.avatar_url(:thumb).to_s %>
            <b><%= link_to r.user.full_name, user_path(r.user) %></b>
          </td>
          <td class="star-rating" data-score= <%= r.rating %> ></td>
        </tr>
        <tr id="review-comment">
          <td class="review"><p><i><%= r.comment.html_safe %></i></p></td>
        </tr>
        <tr>
          <td id="moderation">
             **<%= r.unhelpful? %>
          </td>
        </tr>
      
      <% end %>


    </tbody>
  </table>
</div>



<% if current_user.reviewer? %>

<div id="add_to_list_cont">
  <h3 id="reading-list-header">Add to Reading List</h3>
  <% if @book.claims.include? current_user %>
    <%= link_to "Done reading", unclaim_book_path(@book.id), id: "done-reading-link" %>
    <% else %>
    <%= link_to "Add", claim_book_path(@book.id), id: "add-to-list-link" %>
  <% end %>

  <h2 id="leave-review-header">Leave a Review</h2>


  <% if current_user.reviews.where(book: @book).exists? %>
  <p id="already-reviewed">You've already reviewed this</p>
  <% else %>
    <div id="review-links">
      <%= link_to "Write a review", new_book_review_path(@book.id), style: "color:blue;font-size:15px;" %>
    </div>
</div>
  <% end %>
<% end %>


</body>
<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>