config/routes.rb
Rails.application.routes.draw do


  resources :reviews do
    member do
      put 'helpful' => 'reviews#helpful'
      put 'unhelpful' => 'reviews#unhelpful'
    end
  end

  resources :charges
  resources :genres
  resources :notifications do
    collection do
      post :mark_as_read
   end
 end
  resources :books do
    get :claim, on: :member
    get :unclaim, on: :member
    resources :reviews
  end

  get 'user/:id' => 'users#show', as: 'user'
  get 'reviewers' => 'users#reviewer', as: 'reviewers'
  get 'authors' => 'users#author', as: 'authors'
  get 'current_user' => 'users#profile'
  get 'edit_user' => 'users#edit'
  get 'authors_search', to: 'users#author'
  get 'reviewers_search', to: 'users#reviewer'


  get 'new_author' => 'users#new_author'
  get 'new_reviewer' => 'users#new_reviewer'

  devise_for :users, controllers: {
          sessions: 'users/sessions',
          registrations: 'users/registrations'
        }

  root to: 'home_pages#index'

  get 'admin' => 'reviews#index'


  get 'author_signup' => 'home_pages#author_signup'
  get 'reviewer_signup' => 'home_pages#reviewer_signup'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="rest_of_page">
</div>
<div id="footer">
  Books4Reviews © 2018 All Rights Reserved
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Admin', admin_path, class: 'navbar-brand', style: 'color:white;' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sections <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Reviews', admin_path, style: 'color:black;' %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_signed_in? %>
          <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_admin_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag "application", :recursive => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

  <%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books4reviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <nav>
      <ul id="main-links">
        <li id="home_link"><%= link_to "Books4Reviews", root_path %></li>

        <% if user_signed_in? %>

          <div class="dropdown" data-behavior="notifications">
            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" data-behavior="notifications-link">
              <%= image_tag "icons8-bell-24.png"%><span data-behavior="unread-count"></span>
            </button>
            <div class="dropdown-menu" data-behavior="notification-items">

            </div>
            <%= link_to "mark all as read", mark_as_read_notifications_path(@notifications), id: "mark_as_read", method: :post, style: "color:black;" %>

          </div>

      <ul id="dropdown-container">
        <li><%= image_tag "icons8-menu-50.png"%></li>
          <ul class="user-dropdown">
            <li><%= link_to "Books", books_path %></li>
            <li><%= link_to "Genres", genres_path %></li>
            <li><%= link_to "Reviewers", reviewers_path %></li>
            <li><%= link_to "Authors", authors_path %></li>
            <div class="separated-links">
              <li><%= link_to "Profile", current_user_path, style: "color:black" %></li>
              <li><%= link_to edit_user_path(current_user), style: "color:black" do %>
                <%= image_tag "icons8-automatic-26.png", style: "width:40px;height:40px;" %>
                <% end %>
              </li>
              <li><%= link_to "log out", destroy_user_session_path, method: :delete, style: "color:black" %></li>
            </div>
          </ul>
      </ul>



<% end %>




    </ul>




  </nav>

  <body>
    <div id="site_wrapper">
      <div id="site_content"><%= yield %></div>
      <div id="footer">
          Books4Reviews all rights reserved ©2019 DMB WebDev
      </div>
    </div>
  </body>
  <script>
      document.getElementById("dropdown-container")
      .addEventListener("click", function(){
      document.querySelector(".user-dropdown")
      .style.display = "block";
    });

      
      document.getElementById("site_wrapper")
      .addEventListener("click", function(){
      document.querySelector(".user-dropdown")
      .style.display = "none";
    });

      


      
  </script>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>